### ISSUE TITLE
How can I install it?

### ISSUE THREAD

**Issue by kevin25** [ThunderCls/xHotSpots#1]
I need to use it with x64dbg. However I'm green. Do I need to compile it?

**Comment by ThunderCls** [comment]
You don't need to compile if you don't want to, just grab the compiled version
https://github.com/ThunderCls/xHotSpots/releases

**Comment by Enna1** [comment]
Hi, ThunderCls.
I copy the xHotSpots.dp32 to x64dbg/release/x32/plugins/ directory, but then the x32dbg is crashed.
I tryed lots of x64dbg version.
Could you give a help?

**Comment by ThunderCls** [comment]
You need to have .NET libs installed in your system for this plugin to work. Did you check on those?. Also make sure you are using the plugin in a fresh/updated and with no other plugins x64dbg version
